name: Run Unit Tests

on:
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  unit-tests:
    name: Run Unit test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Use JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-
      - name: Run Unit Tests
        run: |
          ./gradlew test
      - name: Cleanup Gradle Cache
        uses: ./.github/actions/gradle-cleanup
